import type { Metadata } from 'next';
import './globals.css';
import { Nav } from '@/components/shared/nav/nav';
import { NextIntlClientProvider } from 'next-intl';
import { ThemeApplicator } from '@/components/shared/theme';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="antialiased">
        <NextIntlClientProvider>
          <ThemeApplicator />
          <Nav />
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
